# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run unit tests

# wokflow is triggered on following
on:
  # trigger on push to main
  push:
    branches: [ main ]
  # trigger on new PR to main 
  pull_request:
    branches: [ main ]
  # enables manual triggering
  workflow_dispatch:

jobs:
  run-unit-tests:
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        r-version: ["4.1.3", "4.4.3"]
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Set up R ${{ matrix.r-version }}
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.r-version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[tests]
        if [ -f requirements-fhk.txt ]; then pip install -r requirements-fhk.txt; fi
    
    - name: Install R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 2
    
    - name: Test with unittest
      run: |
        python -m pytest
