# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run unit tests

# wokflow is triggered on following
on:
  # trigger on push to main
  push:
    branches: [ main ]
  # trigger on new PR to main 
  pull_request:
    branches: [ main ]
  # enables manual triggering
  workflow_dispatch:

jobs:
  run-unit-tests: 
    
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10.0", "3.11.9"]
        r-version: ["4.1.3", "4.3.3"]
        
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        # cache: 'pip'

    - name: Set up R ${{ matrix.r-version }}
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.r-version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[tests]

    - name: Install R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 2

    # - name: Debug test.R
    #   run: |
    #     echo DEBUGGING R PATHS
    #     Rscript test.R
    #     echo DEBUGGING EVIRONMENT VARIABLES
    #     echo R_HOME: $R_HOME
    #     echo LD_LIBRARY_PATH: $LD_LIBRARY_PATH
    #     echo DEBUGGING CALLING set
    #     set
    #     echo DEBUGGING CALLING printenv
    #     printenv
    # - name: Debug python
    #   run: |
    #     # export LD_LIBRARY_PATH=/opt/R/4.3.3/lib/R/library:$LD_LIBRARY_PATH
    #     export R_HOME=$(R --slave -e 'cat(R.home())')
    #     echo CALLING which R:
    #     which R
    #     python -m rpy2.situation

    # - name: Setup upterm session
    #   uses: lhotari/action-upterm@v1
    #   with:
    #     limit-access-to-actor: true

    # - name: Wait 1 hour
    #   run: sleep 7200

    - name: Debug test.py
      run: |
        python test.py

    
    - name: Test with pytest
      run: |
        python -m pytest
